//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatahubCSteps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatahubCSteps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;schema&quot;: {
        ///		&quot;user&quot;: {
        ///			&quot;type&quot;: &quot;object&quot;,
        ///			&quot;required&quot;: [&quot;name&quot;],
        ///			&quot;properties&quot;: {
        ///				&quot;name&quot;: {
        ///					&quot;type&quot;: &quot;string&quot;
        ///				},
        ///				&quot;address&quot;: {
        ///					&quot;type&quot;: &quot;array&quot;,
        ///					&quot;items&quot;: {
        ///						&quot;$ref&quot;: &quot;#/schema/address&quot;
        ///					}
        ///				}
        ///			}
        ///		},
        ///		&quot;address&quot;: {
        ///			&quot;type&quot;: &quot;object&quot;,
        ///			&quot;properties&quot;: {
        ///				&quot;type&quot;: {
        ///					&quot;type&quot;: &quot;string&quot;,
        ///					&quot;enum&quot;: [&quot;home&quot;, &quot;office&quot;]
        ///				},
        ///				&quot;line1&quot;: {
        ///					&quot;type&quot;: &quot;string&quot;
        ///				}
        ///			}
        ///		}
        ///	}
        ///}
        ///
        ///					}.
        /// </summary>
        internal static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;operationId&quot;: &quot;GetParams&quot;,
        ///	&quot;parameters&quot;: {
        ///		&quot;xsl&quot;: &quot;{xsl}&quot;
        ///	},
        ///	&quot;value-path&quot;: &quot;schema&quot;
        ///}.
        /// </summary>
        internal static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
    }
}
