/*
 * Power BI
 *
 * Power BI Connector
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace DatahubCSteps.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Columns :  IEquatable<Columns>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Columns" /> class.
        /// </summary>
        /// <param name="Schema">Schema.</param>
        public Columns(Object Schema = null)
        {
            this.Schema = Schema;
            
        }

        /// <summary>
        /// Gets or Sets Schema
        /// </summary>
        [DataMember(Name="schema")]
        public Object Schema { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Columns {\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Columns)obj);
        }

        /// <summary>
        /// Returns true if Columns instances are equal
        /// </summary>
        /// <param name="other">Instance of Columns to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Columns other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Schema == other.Schema ||
                    this.Schema != null &&
                    this.Schema.Equals(other.Schema)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Schema != null)
                    hash = hash * 59 + this.Schema.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Columns left, Columns right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Columns left, Columns right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
